"""practice tables

Revision ID: 7be1dc9c4638
Revises: 7eacb6741751
Create Date: 2026-08-28 23:55:50.007330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7be1dc9c4638'
down_revision: Union[str, Sequence[str], None] = '7eacb6741751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('subtitle', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('page_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('show_title', sa.Boolean(), nullable=False),
    sa.Column('start_on_new_page', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_sections_practice_id'), ['practice_id'], unique=False)

    op.create_table('practice_questions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('source_question_id', sa.String(length=36), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('question_number', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('content_snapshot', sa.Text(), nullable=True),
    sa.Column('options_snapshot', sa.JSON(), nullable=True),
    sa.Column('answer_snapshot', sa.Text(), nullable=True),
    sa.Column('explanation_snapshot', sa.Text(), nullable=True),
    sa.Column('source_version', sa.DateTime(), nullable=True),
    sa.Column('is_modified', sa.Boolean(), nullable=False),
    sa.Column('layout_config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['practice_id'], ['practices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['practice_sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_questions_practice_id'), ['practice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_practice_questions_section_id'), ['section_id'], unique=False)

    op.create_table('practice_content_blocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('practice_question_id', sa.String(length=36), nullable=False),
    sa.Column('block_type', sa.String(length=30), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('style_config', sa.JSON(), nullable=True),
    sa.Column('source_asset_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['practice_question_id'], ['practice_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('practice_content_blocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_practice_content_blocks_practice_question_id'), ['practice_question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('practice_content_blocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_content_blocks_practice_question_id'))

    op.drop_table('practice_content_blocks')
    with op.batch_alter_table('practice_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_questions_section_id'))
        batch_op.drop_index(batch_op.f('ix_practice_questions_practice_id'))

    op.drop_table('practice_questions')
    with op.batch_alter_table('practice_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_practice_sections_practice_id'))

    op.drop_table('practice_sections')
    op.drop_table('practices')
    # ### end Alembic commands ###
