"""selection basket tables

Revision ID: 7eacb6741751
Revises: f3a1b2c4d5e6
Create Date: 2026-08-28 23:51:26.744347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7eacb6741751'
down_revision: Union[str, Sequence[str], None] = 'f3a1b2c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('selection_basket_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('basket_id', sa.String(length=36), nullable=False),
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('basket_id', 'question_id', name='uq_basket_question')
    )
    with op.batch_alter_table('selection_basket_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selection_basket_items_basket_id'), ['basket_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_selection_basket_items_question_id'), ['question_id'], unique=False)

    op.create_table('selection_baskets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('selection_baskets')
    with op.batch_alter_table('selection_basket_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selection_basket_items_question_id'))
        batch_op.drop_index(batch_op.f('ix_selection_basket_items_basket_id'))

    op.drop_table('selection_basket_items')
    # ### end Alembic commands ###
